# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hurl < Formula
  desc "Postman for terminal workflows"
  homepage "https://github.com/neil-and-void/hurl"
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.3.6/hurl_Darwin_x86_64.tar.gz"
      sha256 "267714b5f8447c13a9bf07d497d4bee6d26f6d9f21b5f0f7065e25b1d2f09725"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.3.6/hurl_Darwin_arm64.tar.gz"
      sha256 "d816da532a5ec1efd829e480b927bf984641abe1687b58844a9c11c053625790"

      def install
        bin.install "hurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.3.6/hurl_Linux_x86_64.tar.gz"
      sha256 "34a672f492bd6017aa5ba484fc4eccf07aedb0bc42818055d73b55090377b07c"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.3.6/hurl_Linux_arm64.tar.gz"
      sha256 "80601a9854eabc38f0bf7d016199f1de392b1f3ab948da78bd38139441ec1bf1"

      def install
        bin.install "hurl"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing hurl!
    EOS
  end
end
